### ISSUE TITLE
Error when `f[:]` is used in the sort context

### ISSUE THREAD

**Issue by oleksiyskononenko** [h2oai/datatable#3208]
```python
from datatable import dt, f, sort
DT = dt.Frame([[1], [1]])
DT[:, :, sort(f[:])]
```

produces
```python
AssertionError: Assertion 'flags.size() == ncols' failed in src/core/expr/eval_context.cc, line 264
```

**Comment by oleksiyskononenko** [comment]
Actually, even 

```python
DT[:, :, sort(f[:], reverse=[True, False])]
```

will error as 
```python
ValueError: Mismatch between the number of columns (ncols=1) to be sorted and number of elements (nflags=2) in the reverse flag list
```

**Comment by oleksiyskononenko** [comment]
No surprise, that the same error occurs when doing group by.

**Comment by samukweku** [comment]
@oleksiyskononenko it seems this has been fixed: 
```py
In [1]: from datatable import dt, f, sort
   ...: DT = dt.Frame([[1], [1]])
   ...: DT[:, :, sort(f[:])]

   |   C0    C1
   | int8  int8
-- + ----  ----
 0 |    1     1
[1 row x 2 columns]
```

looks ok to close. cant tell what PR fixed this though

**Comment by oleksiyskononenko** [comment]
It is not fixed, you need to build the code in debug mode and the error is still there.

**Comment by oleksiyskononenko** [comment]
Probably it is not that complicated to be fixed... especially that the result in the `release` mode is correct.
