### ISSUE TITLE
Incorrect output for nested reducers

### ISSUE THREAD

**Issue by samukweku** [h2oai/datatable#3417]
Nesting aggregation calls sometimes produces incorrect results

```py
>>> from datatable import dt, f
>>> DT = dt.Frame([1, 2])
>>> DT[:, dt.mean(dt.sum(f.C0))]
   |         C0
   |    float64
-- + ----------
 0 | 2.8823e+18
[1 row x 1 column]
>>> DT[:, dt.sum(dt.mean(f.C0))]
   |          C0
   |     float64
-- + -----------
 0 | 2.31584e+77
[1 row x 1 column]
```

The expected behavior is
```py
>>> DT[:, dt.mean(dt.sum(f.C0))]
   |    C0
   | float64
-- + -----
 0 |     3
[1 row x 1 column]
>>> DT[:, dt.sum(dt.mean(f.C0))]
   |      C0
   | float64
-- + -------
 0 |     1.5
[1 row x 1 column]
```

datatable version: 1.1
python version: 3.9
operating system: linux

**Comment by samukweku** [comment]
Another example - this time for `countna`: 

```py
DT = dt.Frame(G=[1,1,1,2,2,2], V=[None, None, None, None, 3, 5])
DT
   |     G      V
   | int32  int32
-- + -----  -----
 0 |     1     NA
 1 |     1     NA
 2 |     1     NA
 3 |     2     NA
 4 |     2      3
 5 |     2      5
[6 rows x 2 columns]

DT[:, dt.mean(f.V), dt.by(f.G)] # wrong output
   |     G        V
   | int32  float64
-- + -----  -------
 0 |     1       NA
 1 |     2        4
[2 rows x 2 columns]

# expected output
   |     G    V1
   | int32  int8
-- + -----  ----
 0 |     1     1
 1 |     2     0
[2 rows x 2 columns]


#intermediate frame:
DT[:, dt.mean(f.V), dt.by(f.G)]
   |     G        V
   | int32  float64
-- + -----  -------
 0 |     1       NA
 1 |     2        4
[2 rows x 2 columns]


```

**Comment by samukweku** [comment]
the `countna` issue is solved with #3440

**Comment by oleksiyskononenko** [comment]
I guess your example is missing `countna()` function.

**Comment by oleksiyskononenko** [comment]
@samukweku You say `countna()` is wrong, but in your example you use `count()`. The expected result is, at the same time, provided for `countna()`. Could you please check it one more time?

**Comment by oleksiyskononenko** [comment]
This has been resolved for `FExpr`s. Once all the reducers are converted from `Expr` to `FExpr` the problem should be gone

**Comment by samukweku** [comment]
closing this as nested reduction is fixed: 

```py
DT[:, dt.mean(dt.sum(f.C0))]
Out[3]: 
   |      C0
   | float64
-- + -------
 0 |       3
[1 row x 1 column]
```

**Comment by oleksiyskononenko** [comment]
It is only fixed for FExprs and still persists for Exprs, I guess it should only be closed once we get rid of Exprs.
